[versions]
appVersionName = "2.1.1"
appVersionCode = "26"
androidCompileSdk = "34"
androidMinSdk = "26"

aboutlibraries = "10.10.0"
accompanistSystemuicontroller = "0.34.0"
androidnetworktools = "0.4.5.3"
androidxJunit = "1.1.5"
androixUi = "1.6.1"
apacheCommonsNet = "3.10.0"
apacheCommonsVfs = "2.9.0"
appcompat = "1.6.1"
androidxComposeBom = "2024.02.00"
coreKtx = "1.12.0"
datastorePreferences = "1.0.0"
dcerpc = "0.12.0"
documentfile = "1.0.1"
gradle = "8.2.2"
guava = "27.0.1-android"
hiltAndroid = "2.50"
hiltNavigationCompose = "1.1.0"
jcifsNg = "2.1.10"
junit = "4.13.2"
kotlin = "1.9.22"
kotlinCompilerExtension = "1.5.9"
kotlinxCoroutinesAndroid = "1.8.0"
kotlinxSerializationJson = "1.6.3"
ksp = "1.9.22-1.0.17"
lifecycle = "2.7.0"
listenablefuture = "9999.0-empty-to-avoid-conflict-with-guava"
material3 = "1.2.0"
navigationCompose = "2.7.7"
reorderable = "0.9.6"
room = "2.6.1"
smbj = "0.13.0"
timber = "4.7.1" # TODO: Update after supporting Kotlin static call
workRuntimeKtx = "2.9.0"

[libraries]
aboutlibraries = { module = "com.mikepenz:aboutlibraries", version.ref = "aboutlibraries" }
aboutlibraries-compose = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "aboutlibraries" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidnetworktools = { module = "com.github.stealthcopter:androidnetworktools", version.ref = "androidnetworktools" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "androixUi" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androixUi" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androixUi" }
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
apache-commons-net = { module = "commons-net:commons-net", version.ref = "apacheCommonsNet" }
apache-commons-vfs = { module = "org.apache.commons:commons-vfs2-jackrabbit2", version.ref = "apacheCommonsVfs" }
dcerpc = { module = "com.rapid7.client:dcerpc", version.ref = "dcerpc" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
jcifs-ng = { module = "eu.agno3.jcifs:jcifs-ng", version.ref = "jcifsNg" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
listenablefuture = { module = "com.google.guava:listenablefuture", version.ref = "listenablefuture" }
reorderable = { module = "org.burnoutcrew.composereorderable:reorderable", version.ref = "reorderable" }
smbj = { module = "com.hierynomus:smbj", version.ref = "smbj" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
